### ISSUE TITLE
How to get address by lat lng?

### ISSUE THREAD

**Issue by vqquoc** [goong-io/Goong-Geocoder-JS#3]
I am using Geocoder on Google Maps, and get address from latlng

`geocoder.geocode({
                'latLng': latlng
            }`

I didn't find any similar way at goong map docs.

Thanks so much!

**Comment by iBinh** [comment]
please check this out [goong-sdk](https://github.com/goong-io/goong-sdk/blob/master/docs/services.md#geocoding)

**Comment by vqquoc** [comment]
Thanks for the quick reply.

It has been solved.

Thanks!
